export const ENV_NAMES = {
  JWT_SECRET: "JWT_SECRET",
  JWT_EXPIRES_IN: "JWT_EXPIRES_IN",
  SALTS_ROUNDS: "SALTS_ROUNDS",
  DB_HOST: "DB_HOST",
  DB_PORT: "DB_PORT",
  DB_NAME: "DB_NAME",
  DB_USER: "DB_USER",
  DB_PASSWORD: "DB_PASSWORD",
  FRONTEND_SOURCE: "FRONTEND_SOURCE",
  MAIL_PASSWORD: "MAIL_PASSWORD",
  MAIL_ADDRESS: "MAIL_ADDRESS",
  MAIL_SERVICE: "MAIL_SERVICE",
};
