export const ENV_NAMES = {
  JWT_SECRET: "JWT_SECRET",
  JWT_EXPIRES_IN: "JWT_EXPIRES_IN",
  SALTS_ROUNDS: "SALTS_ROUNDS",
  DB_URL: "DB_URL",
  NODE_ENV: "NODE_ENV",
  DB_PASSWORD: "DB_PASSWORD",
  FRONTEND_SOURCE: "FRONTEND_SOURCE",
  MAIL_ADDRESS: "MAIL_ADDRESS",
  MAIL_REFRESH_TOKEN: "MAIL_REFRESH_TOKEN",
  MAIL_CLIENT_SECRET: "MAIL_CLIENT_SECRET",
  MAIL_CLIENT_ID: "MAIL_CLIENT_ID",
  GOOGLE_REDIRECT_URI: "GOOGLE_REDIRECT_URI",
};
