export const ENV_NAMES = {
  JWT_SECRET: "JWT_SECRET",
  JWT_EXPIRES_IN: "JWT_EXPIRES_IN",
  SALTS_ROUNDS: "SALTS_ROUNDS",
  DB_URL: "DB_URL",
  NODE_ENV: "NODE_ENV",
  DB_PASSWORD: "DB_PASSWORD",
  FRONTEND_SOURCE: "FRONTEND_SOURCE",
  MAIL_PASSWORD: "MAIL_PASSWORD",
  MAIL_ADDRESS: "MAIL_ADDRESS",
  MAIL_SERVICE: "MAIL_SERVICE",
  MAIL_HOST: "MAIL_HOST",
  MAIL_PORT: "MAIL_PORT",
};
